---
- hosts: zookservers
  

  tasks:
  - name: download zookeeper
    get_url: url=http://mirror.reverse.net/pub/apache/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz dest=~

  - name: unrachive zookeeper
    unarchive: src=~/zookeeper-3.4.8.tar.gz dest=~ copy=no mode=775
  
  - file: path=~/zookDir state=directory

  - name: copy the zookeeper config file 
    template: src=config_templates/zoo.cfg.j2 dest=~/zookeeper-3.4.8/conf/zoo.cfg mode=775
  
  - name: copy the zookeeper id
    template: src=config_templates/zook-mydataid.j2 dest=~/zookDir/myid mode=775
    
 
    
